<a href="https://colab.research.google.com/github/Anasritz24/ML-lab/blob/main/problem2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def calc_Expectation(a, n):
  prb = 1/n
  sum = 0
  for i in range(0,n):
    sum += (a[i] * prb)

  return float(sum)

#Driver program
n = 6;
a = [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]
expect = calc_Expectation(a, n)
print( "Expectation of array E(X) is : ",expect)

Expectation of array E(X) is :  3.5


In [ ]:
# Program for 1D array
# numpy.mean() method
import numpy as np
arr = [20, 2, 7, 1, 34]
print("The given array is: ", arr)
print("mean of the given array is : ", np.mean(arr))


The given array is:  [20, 2, 7, 1, 34]
mean of the given array is :  12.8


In [ ]:
# Program for 2D array
# numpy.mean() method
import numpy as np
arr = [[14, 17, 12, 33, 44],
[15, 6, 27, 8, 19],
[23, 2, 54, 1, 4, ]]

print("\nmean of arr along the axis = None : ", np.mean(arr))
print("mean of arr along the axis = 0 : ", np.mean(arr, axis = 0))
print("mean of arr along the axis = 1 : ", np.mean(arr, axis = 1))

out_arr = np.arange(3).reshape(3,1)
print("\nout_arr : ", out_arr)
print("mean of arr along the axis = 1: ",np.mean(arr, axis = 1))


mean of arr along the axis = None :  18.6
mean of arr along the axis = 0 :  [17.33333333  8.33333333 31.         14.         22.33333333]
mean of arr along the axis = 1 :  [24.  15.  16.8]

out_arr :  [[0]
 [1]
 [2]]
mean of arr along the axis = 1:  [24.  15.  16.8]


In [ ]:
# Program for 1D array
# Python Program illustrating numpy.std() method
import numpy as np
arr = [20, 2, 7, 1, 341]
print("arr : ", arr)
print("std of arr : ", np.std(arr))
print ("\nMore precision with float32")
print("std of arr : ", np.std(arr, dtype = np.float32))
print ("\nMore accuracy with float64")
print("std of arr : ", np.std(arr, dtype = np.float64))

arr :  [20, 2, 7, 1, 341]
std of arr :  133.57155385784804

More precision with float32
std of arr :  133.57155

More accuracy with float64
std of arr :  133.57155385784804


In [ ]:
#Program for 2D array
# Python Program illustrating
#numpy.std() method
import numpy as np
arr = [[2, 2, 2, 2, 2],
[15, 6, 27, 8, 2],
[23, 2, 54, 1, 2, ],
[11, 44, 34, 7, 2]]

print("\nstd of arr, axis = None : ", np.std(arr))

print("\nstd of arr, axis = 0 : ", np.std(arr, axis = 0))

print("\nstd of arr, axis = 1 : ", np.std(arr, axis = 1))


std of arr, axis = None :  15.3668474320532

std of arr, axis = 0 :  [ 7.56224173 17.68473918 18.59267329  3.04138127  0.        ]

std of arr, axis = 1 :  [ 0.          8.7772433  20.53874388 16.40243884]


In [ ]:
# Python program to get variance of a list
# Importing the NumPy module
import numpy as np

list = [2, 4, 4, 4, 5, 5, 7, 9]

print("\nstd of arr, axis = None : ", np.var(list))




std of arr, axis = None :  4.0


In [ ]:
from numpy import array
from numpy import cov
x = array([1,2,3,4,5,6,7,8,9])
print(x)
y = array([9,8,7,6,5,4,3,2,1])
print(y)
Sigma = cov(x,y)[0,1]
print(Sigma)


[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
-7.5


In [ ]:
from numpy import array
from numpy import cov
x = array([1,2,3,4,5,6,7,8,9])
print(x)
y = array([9,8,7,6,5,4,3,2,1])
print(y)
Sigma = cov(x,y)
print(Sigma)


[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[[ 7.5 -7.5]
 [-7.5  7.5]]
